### PR TITLE
Upgrade swc_core to 0.90.37

### PR DESCRIPTION
**Pull request by AndrewIngram**
Resolves https://github.com/pmndrs/swc-jotai/issues/27

Should make it compatible with Next 14.2.

I've tested this by building the new wasm file and overriding the one in node_modules for debug_label. Not sure what more is needed.

(Based on https://github.com/pmndrs/swc-jotai/pull/29 from @JonathanUsername)

### CODE REVIEW

**Comment by dai-shi** [comment]
@Thisen Are you able to review it?

**Comment by cenobitedk** [comment]
Hi there! There's a ton of people using Next and Jotai and all are blocked from upgrading Next to anything higher than `14.1.4` if they want to maintain a good developer experience.
It would be awesome if you found some time to review @Thisen 😃🙏

**Comment by dai-shi** [comment]
Would anyone volunteer to be a co-maintainer?

**Comment by chrisjh** [comment]
@dai-shi I'd be willing to help out as we're blocked on this as well. Admittedly, rust isn't my area of expertise but seems like the surface area is small enough for me to get a handle on it. I really enjoy using Jotai so feels like the least I could do to give back to the project.

**Comment by dai-shi** [comment]
@chrisjh Thanks for your help.
I think we need someone who is fairly familiar with Rust and SWC.
For a start, I would like someone to implement a github workflow to automate the publish process. Something like this: https://github.com/pmndrs/jotai/pull/2578
Would you be able to work on it?

**Comment by Thisen** [comment]
This looks super great. I promise I'll get it integrated and released this week. 👍🏼

**Pull request merged**
