### PR TITLE
Update swc_core to 0.104.2

### LINKED ISSUE #40: Upgrade swc_core to 0.98
Hi,
thanks a lot for your great work.
I updated Rspack to v1, they are now using swc_core v0.98. (1.70 - 1.7.18)
https://plugins.swc.rs/versions/range/16

Are there plans to upgrade this plugin to a newer swc_core version?
I'm not really into swc stuff, so sadly no clue how much time and effort is necessary.
Thank you for your time!

### PR DESCRIPTION
**Pull request by AsakuraMizu**
Resolve #40

Also extracts `swc_core` dependency into the workspace for easier version management.

### CODE REVIEW

**Comment by dannydtk** [comment]
Hey, it's been opened for almost a month now, any chance of getting this merged?

**Comment by mmichels-brex** [comment]
+1, would be awesome to get this merged!

**Review by Thisen — COMMENTED** [review]
Trying to start CI

**Comment by Thisen** [comment]
Merged in #42

**Pull request closed without merging**
